__title__ = "open_kite_connect"
__description__ = "Fork of the official Kite Connect python client, allowing free access to the api."
__url__ = "https://kite.trade"
__download_url__ = "https://github.com/AnjayGoel/pykiteconnect"
__version__ = "4.0.0"
__author__ = "Anjay Goel"
__author_email__ = "anjay.goel@gmail.com"
__license__ = "MIT"
